"""Référentiel des communes d'Île-de-France pour la détection d'intention.

La liste était auparavant écrite à la main dans intent_detector.py et ne couvrait
que 78 communes sur 1 266. Toute question portant sur une commune absente —
Bobigny, Bagnolet, Sevran, Stains, Rosny — n'était pas reconnue, et le détecteur
retombait sur son intention par défaut : le classement régional par qualité de
vie. Demander « Bobigny ? » renvoyait donc Neuilly-sur-Seine et Saint-Mandé.

Le référentiel est désormais généré depuis la base et couvre les 1 266 communes.
Régénération :
    python3 chatbot/generer_communes.py > chatbot/communes_idf.py
"""

# Généré le 20 juillet 2026 depuis communes_agregat (1 266 communes).
COMMUNES_IDF = [
    'Saint-Martin-de-Bréthencourt',
    'Saint-Jean-les-Deux-Jumeaux',
    'Vieille-Église-en-Yvelines',
    'Aubepierre-Ozouer-le-Repos',
    'Saint-Germain-de-la-Grange',
    'Clairefontaine-en-Yvelines',
    'Saint-Maurice-Montcouronne',
    'Saint-Germain-lès-Arpajon',
    'Saint-Sulpice-de-Favières',
    'Vernou-la-Celle-sur-Seine',
    'Saint-Thibault-des-Vignes',
    'Grandpuits-Bailly-Carrois',
    'La Chapelle-Saint-Sulpice',
    'Louan-Villegruis-Fontaine',
    'Saint-Germain-lès-Corbeil',
    'Sainte-Geneviève-des-Bois',
    'Villeneuve-sous-Dammartin',
    'Saint-Arnoult-en-Yvelines',
    'Conflans-Sainte-Honorine',
    'Saint-Mars-Vieux-Maisons',
    'Courdimanche-sur-Essonne',
    'Saint-Rémy-lès-Chevreuse',
    'Saint-Pierre-lès-Nemours',
    'Saint-Fargeau-Ponthierry',
    'La Villeneuve-en-Chevrie',
    'Chennevières-lès-Louvres',
    'Saint-Jean-de-Beauregard',
    'Villeneuve-Saint-Georges',
    'Maisoncelles-en-Gâtinais',
    'Tessancourt-sur-Aubette',
    'Saint-Martin-des-Champs',
    'Saint-Martin-du-Boschet',
    'Le Chesnay-Rocquencourt',
    'Montigny-lès-Cormeilles',
    'Saint-Sauveur-sur-École',
    'Lorrez-le-Bocage-Préaux',
    'Le Tremblay-sur-Mauldre',
    'Ballancourt-sur-Essonne',
    'Les Pavillons-sous-Bois',
    'Guigneville-sur-Essonne',
    'Villiers-Saint-Frédéric',
    'Saint-Germain-sur-Morin',
    'Saint-Germain-sous-Doue',
    'Saint-Germain-sur-École',
    'Saint-Martin-la-Garenne',
    'Saint-Martin-des-Champs',
    'Saint-Léger-en-Yvelines',
    'Villeneuve-Saint-Denis',
    'Saint-Martin-du-Tertre',
    'Montigny-le-Bretonneux',
    'Couilly-Pont-aux-Dames',
    'Gironville-sur-Essonne',
    'Soisy-sous-Montmorency',
    'La Madeleine-sur-Loing',
    'Congerville-Thionville',
    'Chaufour-lès-Bonnières',
    'Villiers-Saint-Georges',
    'Lumigny-Nesles-Ormeaux',
    'Follainville-Dennemont',
    'Oinville-sur-Montcient',
    'Moret-Loing-et-Orvanne',
    'Saint-Pierre-du-Perray',
    'Saint-Rémy-de-la-Vanne',
    'Saint-Illiers-la-Ville',
    'Beauchery-Saint-Martin',
    'Chauconin-Neufmontiers',
    'Saint-Sauveur-lès-Bray',
    'Saint-Brice-sous-Forêt',
    'Saint-Cyr-sous-Dourdan',
    'Chennevières-sur-Marne',
    'Saint-Denis-lès-Rebais',
    'Germigny-sous-Coulombs',
    'Le Plessis-Feu-Aussoux',
    'Villeneuve-sur-Bellot',
    'Dampierre-en-Yvelines',
    'Saint-Michel-sur-Orge',
    'Congis-sur-Thérouanne',
    'Villeneuve-les-Bordes',
    'Carrières-sous-Poissy',
    'Rochefort-en-Yvelines',
    'Arnouville-lès-Mantes',
    'Villeneuve-la-Garenne',
    'Villeneuve-sur-Auvers',
    'Gaillon-sur-Montcient',
    'Bailly-Romainvilliers',
    'Voisins-le-Bretonneux',
    'Saint-Nom-la-Bretèche',
    'Les Chapelles-Bourbon',
    'Saint-Illiers-le-Bois',
    'Saint-Martin-en-Bière',
    'Saint-Germain-en-Laye',
    'Le Mesnil-Saint-Denis',
    'Boinville-le-Gaillard',
    'Les Ormes-sur-Voulzie',
    'Montereau-sur-le-Jard',
    'Montereau-Fault-Yonne',
    'Montceaux-lès-Provins',
    'La Ferté-sous-Jouarre',
    'Courcelles-sur-Viosne',
    'Cormeilles-en-Parisis',
    'Saint-Maur-des-Fossés',
    'Villemoisson-sur-Orge',
    'Auffreville-Brasseuil',
    'Plessis-Saint-Benoist',
    'Condé-Sainte-Libiaire',
    'La Forêt-Sainte-Croix',
    'Chauffour-lès-Étréchy',
    'Boissy-sous-Saint-Yon',
    'Le Tertre-Saint-Denis',
    'Chanteloup-les-Vignes',
    'La Queue-les-Yvelines',
    'Le Perray-en-Yvelines',
    'Dammartin-sur-Tigeaux',
    'Saint-Ouen-sur-Morin',
    'Boulogne-Billancourt',
    'Maisoncelles-en-Brie',
    'Verrières-le-Buisson',
    'Le Val-Saint-Germain',
    'Vulaines-lès-Provins',
    'La Celle-Saint-Cloud',
    'La Chapelle-Gauthier',
    'Sognolles-en-Montois',
    'Le Plessis-Luzarches',
    'Saint-Cyr-la-Rivière',
    'Boissise-la-Bertrand',
    'Les Clayes-sous-Bois',
    'Boutigny-sur-Essonne',
    'Marolles-en-Hurepoix',
    'Saint-Clair-sur-Epte',
    'Saint-Cyr-en-Arthies',
    'Brou-sur-Chantereine',
    'Auvers-Saint-Georges',
    "D'Huison-Longueville",
    'Le Coudray-Montceaux',
    'Nainville-les-Roches',
    'Boussy-Saint-Antoine',
    'Notre-Dame-de-la-Mer',
    'Abbéville-la-Rivière',
    'Montigny-le-Guesdier',
    'Villenauxe-la-Petite',
    'Saint-Ouen-sur-Seine',
    'Conches-sur-Gondoire',
    'Neufmoutiers-en-Brie',
    'La Chapelle-la-Reine',
    'Gretz-Armainvilliers',
    'Boinville-en-Mantois',
    'La Chapelle-en-Vexin',
    'Moncourt-Fromonville',
    'Évry-Grégy-sur-Yerre',
    'Jouars-Pontchartrain',
    'Bazoches-sur-Guyonne',
    'Beaumont-du-Gâtinais',
    'Courcelles-en-Bassée',
    'Le Perreux-sur-Marne',
    'Le Pré-Saint-Gervais',
    'Villaines-sous-Bois',
    'Chalautre-la-Grande',
    'Saint-Germain-Laxis',
    'Ville-Saint-Jacques',
    'La Chapelle-Moutils',
    'La Celle-les-Bordes',
    'Fontenay-Saint-Père',
    'Neauphle-le-Château',
    'Vélizy-Villacoublay',
    'Villennes-sur-Seine',
    'Brières-les-Scellés',
    'Fontaine-la-Rivière',
    'Fontenay-le-Vicomte',
    'Paray-Vieille-Poste',
    'La Brosse-Montceaux',
    'Villebon-sur-Yvette',
    'Gesvres-le-Chapitre',
    'Champigny-sur-Marne',
    'Armentières-en-Brie',
    'La Chapelle-Rablais',
    'Cormeilles-en-Vexin',
    'Fontenay-en-Parisis',
    'Hérouville-en-Vexin',
    'Le Châtelet-en-Brie',
    'La Houssaye-en-Brie',
    'Montceaux-lès-Meaux',
    'Bussy-Saint-Georges',
    'Le Plessis-aux-Bois',
    "Le Plessis-l'Évêque",
    'Saint-Germain-Laval',
    'Champagne-sur-Seine',
    'Bonnières-sur-Seine',
    'Donnemarie-Dontilly',
    'Villeneuve-le-Comte',
    'Le Plessis-Robinson',
    "Saint-Rémy-l'Honoré",
    'La Garenne-Colombes',
    'Issy-les-Moulineaux',
    'Chalautre-la-Petite',
    'Le Plessis-Bouchard',
    'Mousseaux-sur-Seine',
    'Bannost-Villegagnon',
    'Nanteau-sur-Essonne',
    "Saint-Ouen-l'Aumône",
    'Épinay-Champlâtreux',
    'Saint-Cyr-sur-Morin',
    'Carrières-sur-Seine',
    'Saulx-les-Chartreux',
    'La Frette-sur-Seine',
    'Wy-dit-Joli-Village',
    'Isles-les-Meldeuses',
    'Châtenay-sur-Seine',
    'Isles-lès-Villenoy',
    'Les Loges-en-Josas',
    'Les Essarts-le-Roi',
    'Aulnay-sur-Mauldre',
    'Chanteloup-en-Brie',
    'Puiselet-le-Marais',
    'Prunay-sur-Essonne',
    'Meulan-en-Yvelines',
    'Villiers-le-Mahieu',
    'Lainville-en-Vexin',
    'Coulombs-en-Valois',
    'Flins-Neuve-Église',
    'Bussy-Saint-Martin',
    'Bagneaux-sur-Loing',
    'Dammartin-en-Goële',
    'Quincy-sous-Sénart',
    'Béthemont-la-Forêt',
    'Vulaines-sur-Seine',
    'Fontenay-sous-Bois',
    'Ormesson-sur-Marne',
    'Mousseaux-lès-Bray',
    'Asnières-sur-Seine',
    'Châtenay-en-France',
    'Fontenay-Mauvoisin',
    'Villiers-sur-Seine',
    'Épinay-sous-Sénart',
    'Bonneuil-en-France',
    'Marolles-sur-Seine',
    'Nanteuil-lès-Meaux',
    'Prunay-en-Yvelines',
    'Thorigny-sur-Marne',
    'Janville-sur-Juine',
    'Épiais-lès-Louvres',
    'Boissy-aux-Cailles',
    'Boissy-Saint-Léger',
    'Le Plessis-Trévise',
    'Saint-Just-en-Brie',
    'Bonneuil-sur-Marne',
    'Champagne-sur-Oise',
    'Soignolles-en-Brie',
    'La Boissière-École',
    'Montreuil-sur-Epte',
    'Montigny-sur-Loing',
    'Verneuil-sur-Seine',
    'Varennes-sur-Seine',
    'Maudétour-en-Vexin',
    'Saint-Ouen-en-Brie',
    'Chenoise-Cucharmoy',
    'Mareil-sur-Mauldre',
    'Saint-Leu-la-Forêt',
    'Nanteuil-sur-Marne',
    'Évry-Courcouronnes',
    'Breuil-Bois-Robert',
    'Saint-Loup-de-Naud',
    'Nanteau-sur-Lunain',
    'Fontenay-lès-Briis',
    'Villiers-sous-Grez',
    'Vayres-sur-Essonne',
    'Tremblay-en-France',
    'Villers-en-Arthies',
    'Le Kremlin-Bicêtre',
    'Villiers-sur-Morin',
    'Marolles-en-Beauce',
    'Les Granges-le-Roi',
    'Dammartin-en-Serve',
    'Garges-lès-Gonesse',
    'Le Bellay-en-Vexin',
    'Fontenay-aux-Roses',
    'Marnes-la-Coquette',
    'Châtillon-la-Borde',
    'Bruyères-le-Châtel',
    'La Celle-sur-Morin',
    'Mézières-sur-Seine',
    'Les Alluets-le-Roi',
    'Villiers-sur-Marne',
    'La Grande-Paroisse',
    'Fontenay-le-Fleury',
    'Sancy-lès-Provins',
    'Villiers-en-Bière',
    'Grisy-les-Plâtres',
    'Saintry-sur-Seine',
    'Charenton-le-Pont',
    'Leuville-sur-Orge',
    "L'Île-Saint-Denis",
    'Enghien-les-Bains',
    'Longpont-sur-Orge',
    'Boissy-la-Rivière',
    'Boissy-sans-Avoir',
    'Gournay-sur-Marne',
    'Beaumont-sur-Oise',
    'Villeneuve-le-Roi',
    'Croissy-sur-Seine',
    "Germigny-l'Évêque",
    'Ozoir-la-Ferrière',
    'Morigny-Champigny',
    'Crécy-la-Chapelle',
    'Croissy-Beaubourg',
    "Boissy-l'Aillerie",
    'Fontenay-Trésigny',
    'Ferrières-en-Brie',
    'Briis-sous-Forges',
    'Magny-les-Hameaux',
    'Neuilly-sur-Seine',
    "Saint-Cyr-l'École",
    'Joinville-le-Pont',
    'Souppes-sur-Loing',
    'Herblay-sur-Seine',
    'Savigny-le-Temple',
    'Fresnes-sur-Marne',
    'Le Plessis-Gassot',
    'Thiverval-Grignon',
    'Villiers-sur-Orge',
    'Mandres-les-Roses',
    'Baillet-en-France',
    'Villiers-le-Bâcle',
    'Vigneux-sur-Seine',
    'Pontault-Combault',
    'Mareuil-lès-Meaux',
    'Fontaine-Fourches',
    'Nerville-la-Forêt',
    'Morsang-sur-Seine',
    'Le Tartre-Gaudran',
    'Boullay-les-Troux',
    'Brétigny-sur-Orge',
    'Bruyères-sur-Oise',
    'Neuville-sur-Oise',
    'Changis-sur-Marne',
    'Cessoy-en-Montois',
    'Chevry-en-Sereine',
    'Courson-Monteloup',
    'Brie-Comte-Robert',
    "Montfort-l'Amaury",
    'Neauphle-le-Vieux',
    'Crèvecœur-en-Brie',
    'Ozouer-le-Voulgis',
    'Puiseux-en-France',
    'Neuilly-sur-Marne',
    'Milon-la-Chapelle',
    'Asnières-sur-Oise',
    'Bazoches-lès-Bray',
    'Vienne-en-Arthies',
    'Neuilly-Plaisance',
    'Bouray-sur-Juine',
    'Montalet-le-Bois',
    'Saint-Barthélemy',
    'Limeil-Brévannes',
    'Marolles-en-Brie',
    'Nogent-sur-Marne',
    'La Queue-en-Brie',
    "Verneuil-l'Étang",
    'Maisons-Laffitte',
    'Aulnay-sous-Bois',
    'Boissy-le-Châtel',
    'Bures-sur-Yvette',
    'Authon-la-Plaine',
    'Beautheil-Saints',
    'Gometz-le-Châtel',
    "L'Étang-la-Ville",
    'Corbeil-Essonnes',
    'Mareil-en-France',
    'Toussus-le-Noble',
    'Savigny-sur-Orge',
    'Neuilly-en-Vexin',
    'Montigny-Lencoup',
    'Chevrainvilliers',
    'Bourron-Marlotte',
    'Nesles-la-Vallée',
    'Morsang-sur-Orge',
    'Chalou-Moulineux',
    'Boissy-Mauvoisin',
    'Achères-la-Forêt',
    'Limoges-Fourches',
    'Trocy-en-Multien',
    'Arbonne-la-Forêt',
    'Vaires-sur-Marne',
    'Chalo-Saint-Mars',
    'Forges-les-Bains',
    'Marolles-en-Brie',
    'Ormoy-la-Rivière',
    'La Chapelle-Iger',
    'Férolles-Attilly',
    'Vert-Saint-Denis',
    'La Croix-en-Brie',
    'Moigny-sur-École',
    'Condé-sur-Vesgre',
    'Le Plessis-Placy',
    'Le Mesnil-le-Roi',
    'Le Mée-sur-Seine',
    'Roissy-en-France',
    'Puiseux-Pontoise',
    'La Ville-du-Bois',
    'Prunay-le-Temple',
    'Champs-sur-Marne',
    'Levallois-Perret',
    'Châtenay-Malabry',
    'Samois-sur-Seine',
    'Le Mesnil-Amelot',
    'La Ferté-Gaucher',
    'Chailly-en-Bière',
    'Clichy-sous-Bois',
    'Dammarie-les-Lys',
    'Épinay-sur-Seine',
    'Belloy-en-France',
    'Fontaine-le-Port',
    'La Haute-Maison',
    'Magny-le-Hongre',
    'Vieux-Champagne',
    'Thoury-Férottes',
    'Mons-en-Montois',
    'Moissy-Cramayel',
    'La Forêt-le-Roi',
    'Rueil-Malmaison',
    'Noisy-sur-École',
    'Noyen-sur-Seine',
    'Annet-sur-Marne',
    'Jagny-sous-Bois',
    'Épinay-sur-Orge',
    'Jouy-le-Moutier',
    'Fleury-en-Bière',
    'Liverdy-en-Brie',
    'Valence-en-Brie',
    'Villiers-le-Sec',
    'Boissise-le-Roi',
    'Livry-sur-Seine',
    'Villiers-le-Bel',
    'Le Plessis-Pâté',
    'Mantes-la-Jolie',
    'Boissy-le-Cutté',
    'Mantes-la-Ville',
    'Ablon-sur-Seine',
    'Crégy-lès-Meaux',
    'Saint-Soupplets',
    'Soisy-sur-Seine',
    'Auvers-sur-Oise',
    'Gurcy-le-Châtel',
    'Cernay-la-Ville',
    'Passy-sur-Seine',
    'Crouy-sur-Ourcq',
    'Rosny-sur-Seine',
    'Rosny-sous-Bois',
    'Chaumes-en-Brie',
    'Chailly-en-Brie',
    'Triel-sur-Seine',
    "L'Haÿ-les-Roses",
    'Flins-sur-Seine',
    'Le Blanc-Mesnil',
    'Presles-en-Brie',
    'Poigny-la-Forêt',
    'Paray-Douaville',
    'Vitry-sur-Seine',
    'Faÿ-lès-Nemours',
    'Précy-sur-Marne',
    'Chevry-Cossigny',
    'Moussy-le-Vieux',
    'Vaux-sur-Lunain',
    'Bernes-sur-Oise',
    'Grisy-sur-Seine',
    'Montgé-en-Goële',
    'Lévis-Saint-Nom',
    'Tournan-en-Brie',
    'Saâcy-sur-Marne',
    'Saint-Escobille',
    'Brueil-en-Vexin',
    'Lagny-sur-Marne',
    'Ballainvilliers',
    'Le Mesnil-Aubry',
    'Mareil-le-Guyon',
    'Juvisy-sur-Orge',
    'Gometz-la-Ville',
    'Soisy-sur-École',
    'Souzy-la-Briche',
    'Quincy-Voisins',
    'Leudon-en-Brie',
    'Ussy-sur-Marne',
    'Orly-sur-Morin',
    'May-en-Multien',
    'Misy-sur-Yonne',
    'Morainvilliers',
    'Chatignonville',
    'Vaux-sur-Seine',
    'Les Bréviaires',
    'Marles-en-Brie',
    'Chilly-Mazarin',
    'Jouy-Mauvoisin',
    'Mary-sur-Marne',
    'Melz-sur-Seine',
    'La Ferté-Alais',
    'Fleury-Mérogis',
    'Buno-Bonnevaux',
    'Gif-sur-Yvette',
    'Civry-la-Forêt',
    'Le Mérévillois',
    'Milly-la-Forêt',
    'Oncy-sur-École',
    'Moussy-le-Neuf',
    'Choisy-en-Brie',
    'Mouy-sur-Seine',
    'Treuzy-Levelay',
    'Varennes-Jarcy',
    'La Roche-Guyon',
    'Noisy-Rudignon',
    'Guiry-en-Vexin',
    'Augers-en-Brie',
    'Viry-Châtillon',
    'Bourg-la-Reine',
    'Saulx-Marchais',
    'Lizy-sur-Ourcq',
    'Chevilly-Larue',
    'Boutervilliers',
    'Noisy-le-Grand',
    'Ivry-sur-Seine',
    'Maisons-Alfort',
    'Vaudoy-en-Brie',
    'Méry-sur-Marne',
    'Beton-Bazoches',
    'Bray-sur-Seine',
    'Saint-Hilliers',
    'Butry-sur-Oise',
    'Saint-Hilarion',
    'Cléry-en-Vexin',
    'Deuil-la-Barre',
    'Mézy-sur-Seine',
    'Grez-sur-Loing',
    'Vincy-Manœuvre',
    'Château-Landon',
    'Magny-en-Vexin',
    'Noisy-sur-Oise',
    'Bernay-Vilbert',
    'Marly-la-Ville',
    'Sainte-Colombe',
    'Saint-Augustin',
    'Combs-la-Ville',
    'Jouy-le-Châtel',
    'Jouy-sur-Morin',
    'Roissy-en-Brie',
    'Échouboulains',
    'Rozay-en-Brie',
    'Vallangoujard',
    'Cheptainville',
    'Villiers-Adam',
    "Ville-d'Avray",
    'Jouy-en-Josas',
    'Signy-Signets',
    'Vert-le-Grand',
    'Claye-Souilly',
    'Angervilliers',
    'Vaux-le-Pénil',
    'Laval-en-Brie',
    'Fontainebleau',
    'Saint-Gervais',
    'Garentreville',
    'Boissy-le-Sec',
    'Bois-Colombes',
    'Reuil-en-Brie',
    'Méry-sur-Oise',
    'Sivry-Courtry',
    'Goussainville',
    'Le Port-Marly',
    'Cannes-Écluse',
    'Saint-Hilaire',
    'Clos-Fontaine',
    'Saint-Maurice',
    'Bry-sur-Marne',
    'Saint-Lambert',
    'Perdreauville',
    'Limetz-Villez',
    'Vert-le-Petit',
    'Villemaréchal',
    'Grisy-Suisnes',
    'Aubergenville',
    'Bellefontaine',
    'Douy-la-Ramée',
    'Gennevilliers',
    'Saint-Gratien',
    'Hondevilliers',
    'Aubervilliers',
    'La Hauteville',
    'Choisy-le-Roi',
    'Sucy-en-Brie',
    'Lescherolles',
    'Goussonville',
    'Villetaneuse',
    'Hautefeuille',
    'Saint-Fiacre',
    'Théméricourt',
    'Courquetaine',
    'Longvilliers',
    'Livry-Gargan',
    'La Courneuve',
    'Sainte-Mesme',
    'Noisy-le-Sec',
    'Champmotteux',
    'Brignancourt',
    'Saint-Pathus',
    'Saint-Mammès',
    'Faremoutiers',
    'Saint-Siméon',
    'Haravilliers',
    'Montainville',
    'Ronquerolles',
    'Émerainville',
    'Villeparisis',
    'Courdimanche',
    'Sainte-Aulde',
    'Saint-Chéron',
    'Guercheville',
    'Roinvilliers',
    'Les Molières',
    'Villemareuil',
    'Boinvilliers',
    'Franconville',
    'Frémainville',
    'Les Écrennes',
    'Goupillières',
    'Giremoutiers',
    'La Genevraye',
    'Pierre-Levée',
    'Guitrancourt',
    'Mittainville',
    'Sablonnières',
    'Mareil-Marly',
    'Noisy-le-Roi',
    'Louveciennes',
    'Marly-le-Roi',
    'Vaugrigneuse',
    'Tacoignières',
    'Sartrouville',
    'Maison-Rouge',
    'Saint-Forget',
    'Fontenailles',
    'Saint-Mesmes',
    'Feucherolles',
    'Châteaubleau',
    'Villecresnes',
    'Gargenville',
    'Charmentray',
    'Magnanville',
    'Montchauvet',
    'Les Mureaux',
    'Neauphlette',
    'Porcheville',
    'Châteaufort',
    'Rennemoulin',
    'Coutevroult',
    'Vernouillet',
    'Avrainville',
    'Boigneville',
    'Aufferville',
    'Bazainville',
    'Monnerville',
    'La Norville',
    'Ollainville',
    'Saint-Aubin',
    'Romainville',
    'Saint-Denis',
    'Villemomble',
    'Saint-Mandé',
    'Attainville',
    'Bessancourt',
    'Genainville',
    "L'Isle-Adam",
    'Saint-Cloud',
    'Montgeroult',
    'Mauperthuis',
    'Montmorency',
    'Longperrier',
    'La Rochette',
    'Saint-Brice',
    'Bois-le-Roi',
    'La Trétoire',
    'Vaucourtois',
    "Bois-d'Arcy",
    'Champcenest',
    'Luisetaines',
    'Flexanville',
    'Mondreville',
    'Les Mesnuls',
    'Gambaiseuil',
    'La Verrière',
    'Marchémoret',
    'Chartrettes',
    'Coulommiers',
    'Mondreville',
    'Montfermeil',
    'Saint-Léger',
    'Vaudherland',
    'Valpuiseaux',
    'Nantouillet',
    'Boulancourt',
    'Bois-Herpin',
    'Seraincourt',
    'Évecquemont',
    'Jumeauville',
    'Survilliers',
    'Montmachoux',
    'Ponthévrard',
    'Richarville',
    'Rambouillet',
    'Montdauphin',
    'Longueville',
    'Chaintreaux',
    'Allainville',
    'Hardricourt',
    'Ris-Orangis',
    'Épiais-Rhus',
    'Saint-Vrain',
    'Alfortville',
    'Argentières',
    'Chartronges',
    'Garancières',
    'Champdeuil',
    'Amenucourt',
    'Herbeville',
    'Labbeville',
    'Villepreux',
    'Les Marêts',
    'Pierrelaye',
    'Dannemarie',
    'Arnouville',
    'Hédouville',
    'Ambleville',
    'Courbevoie',
    'Vaucresson',
    'Mondeville',
    'Le Bourget',
    'Chalmaison',
    'Ecquevilly',
    'Versailles',
    'Le Heaulme',
    'Haute-Isle',
    'Villevaudé',
    'Mitry-Mory',
    'Angerville',
    'Grandchamp',
    'Athis-Mons',
    'Menouville',
    'Chamarande',
    'Champcueil',
    'Soisy-Bouy',
    'Frémécourt',
    'Arronville',
    'Argenteuil',
    'Guermantes',
    'Montlignon',
    'Amponville',
    'Bennecourt',
    'Crespières',
    'Orsonville',
    'Montévrain',
    'Maurecourt',
    'Le Vésinet',
    'Autouillet',
    'Le Vaudoué',
    'Le Perchay',
    'Condécourt',
    'Guibeville',
    'Coignières',
    'Gommecourt',
    'Hargeville',
    'Ménerville',
    'Marcoussis',
    'Chaumontel',
    'Breux-Jouy',
    'Saint-Mard',
    'Bray-et-Lû',
    'Montolivet',
    'Bouffémont',
    'Arrancourt',
    'Boissettes',
    'Gironville',
    'Bassevelle',
    'Orvilliers',
    'Seine-Port',
    'Remauville',
    'Richebourg',
    'Moisselles',
    'Sept-Sorts',
    'Adainville',
    'Rolleboise',
    'Valmondois',
    'Saint-Méry',
    'Le Thillay',
    'Guyancourt',
    'La Falaise',
    'Obsonville',
    'Saint-Witz',
    'Longjumeau',
    'Saint-Prix',
    'Villepinte',
    'Chambourcy',
    'Guillerval',
    'Livilliers',
    'Grosrouvre',
    'Trilbardou',
    'Villeconin',
    'Leudeville',
    'Mauregard',
    'Vauhallan',
    'Menucourt',
    'Mauchamps',
    'Frouville',
    'Dormelles',
    'Auffargis',
    'Pontcarré',
    'Ézanville',
    'Montlhéry',
    'Theuville',
    'Courances',
    'Montenils',
    'Chevreuse',
    'Montmagny',
    'Villejust',
    'Luzarches',
    'Longuesse',
    'Villecerf',
    'Gouvernes',
    'Jambville',
    'Bussières',
    'Montrouge',
    'Le Raincy',
    'Coulommes',
    'Fublaines',
    'Palaiseau',
    'Voulangis',
    'Millemont',
    'Guerville',
    'Châtillon',
    'Coutençon',
    'Varreddes',
    'Omerville',
    'Bondoufle',
    'Itteville',
    'Les Lilas',
    'Courtacon',
    'Courchamp',
    'Bougligny',
    'Auvernaux',
    'Montreuil',
    'Courtomer',
    'Champeaux',
    'Courpalay',
    'Maffliers',
    'Vincennes',
    'Génicourt',
    'Pecqueuse',
    'Égreville',
    'Saint-Yon',
    'Villejuif',
    'Pézarches',
    'Aigremont',
    'Breuillet',
    'Chalifert',
    'Vimpelles',
    'Bouqueval',
    'Frépillon',
    'Bourdonné',
    'Montgeron',
    'Rampillon',
    'Roinville',
    'Boisemont',
    'Méricourt',
    'Montesson',
    'Étrépilly',
    'Montsoult',
    'Chevannes',
    'Corbreuse',
    'Villebéon',
    'Bonnelles',
    'Dannemois',
    'Beauchamp',
    'Collégien',
    'Lieusaint',
    'Élancourt',
    'Meilleray',
    'Sarcelles',
    'Jossigny',
    'Fontains',
    'Dampmart',
    'Bouleurs',
    'Samoreau',
    'Margency',
    'Trilport',
    'Penchard',
    'Boissets',
    'Châtenoy',
    'Villenoy',
    'Chamigny',
    'Léchelle',
    'Maulette',
    'Villemer',
    'Orcemont',
    'Rupéreux',
    'Chavenay',
    'Soindres',
    'Jablines',
    'Cocherel',
    'Courgent',
    'Chérence',
    'Rubelles',
    'Favières',
    'Aincourt',
    'Ableiges',
    'Valenton',
    'Voisenon',
    'Vendrest',
    'Recloses',
    'Barbizon',
    'Gentilly',
    'Beauvoir',
    'Marcilly',
    'Vaujours',
    'Monthyon',
    'Pomponne',
    'Pommeuse',
    'La Tombe',
    'Viroflay',
    'Puisieux',
    'Nanterre',
    'Étiolles',
    'Mespuits',
    'Ormesson',
    'Sammeron',
    'Coupvray',
    'Suresnes',
    'Colombes',
    'Sonchamp',
    'Chaville',
    'Villeroy',
    'Voinsles',
    'Charmont',
    'Les Ulis',
    'Darvault',
    'Pontoise',
    'Videlles',
    'Sermaise',
    'Buthiers',
    'Chauffry',
    'Santeuil',
    'Hermeray',
    'Mortcerf',
    'Freneuse',
    'Vétheuil',
    'Houilles',
    'Mérobert',
    'Flacourt',
    'Carnetin',
    'Bouville',
    'Bazemont',
    'Vinantes',
    'Bezalles',
    'Écharcon',
    'Eaubonne',
    'Meigneux',
    'Champlan',
    'Andrezel',
    'Bougival',
    'Boutigny',
    'Morangis',
    'Favrieux',
    'Villette',
    'Buchelay',
    'Drocourt',
    'Septeuil',
    'Senlisse',
    'Malakoff',
    'Berville',
    'Banthelu',
    'Bagnolet',
    'Bréançon',
    'Maurepas',
    'Moisenay',
    'Vanvillé',
    'Verdelot',
    'Machault',
    'Nonville',
    'Ocquerre',
    'Bransles',
    'Crisenoy',
    'Villeron',
    'Larchant',
    'Mouroux',
    'Juziers',
    'Presles',
    'Achères',
    'Noisiel',
    'Tigeaux',
    'Poligny',
    'Créteil',
    'Châtres',
    'Fresnes',
    'Amillis',
    'Sannois',
    'Gambais',
    'Galluis',
    'Arville',
    'Compans',
    'Rouilly',
    'Noiseau',
    'Marines',
    'Boisdon',
    'Périgny',
    'Taverny',
    'Mormant',
    'Viarmes',
    'Santeny',
    'Mennecy',
    'Cravent',
    'Jutigny',
    'Trappes',
    'Chaussy',
    'Lommoye',
    'Orgeval',
    'Courtry',
    'Orgerus',
    'Limours',
    'Commeny',
    'Arcueil',
    'Moisson',
    'Sourdun',
    'Parmain',
    'Oissery',
    'Jouarre',
    'Mulcent',
    'Béhoust',
    'Villuis',
    'Jaulnes',
    'Lésigny',
    'Avernes',
    'Rouvres',
    'Étréchy',
    'Choisel',
    'Auteuil',
    'Lesches',
    'Draveil',
    'Longnes',
    'Dourdan',
    'Guérard',
    'Gastins',
    'Lizines',
    'Gazeran',
    'Coubert',
    'Bouafle',
    'Blennes',
    'Perthes',
    'Étampes',
    'Guignes',
    'Égligny',
    'Wissous',
    'Gonesse',
    'Andilly',
    'Groslay',
    'Vignely',
    'Cerneux',
    'Touquin',
    'Guernes',
    'Bullion',
    'Arpajon',
    'Fromont',
    'Bièvres',
    'Jaignes',
    'Chauvry',
    'Nointel',
    'Thomery',
    'Thénisy',
    'Louvres',
    'Le Pecq',
    'Plaisir',
    'Luzancy',
    'Nucourt',
    'Chelles',
    'Gressey',
    'Raizeux',
    'Boitron',
    'Tousson',
    'Garches',
    'Coubron',
    'Voulton',
    'Puteaux',
    'Arthies',
    'Clamart',
    'Bobigny',
    'Chambry',
    'Bagneux',
    'Vauréal',
    'Mortery',
    'Tancrou',
    'Andrésy',
    'Provins',
    'Nemours',
    'Villabé',
    'Juilly',
    'Grigny',
    'Yèbles',
    'Beynes',
    'Maincy',
    'Piscop',
    'Rungis',
    'Héricy',
    'Bezons',
    'Bombon',
    'Maisse',
    'Chenou',
    'Barbey',
    'Vémars',
    'Iverny',
    'Orveau',
    'Pussay',
    'Charny',
    'Thiais',
    'Servon',
    'Balloy',
    'Serris',
    'Salins',
    'Nangis',
    'Clichy',
    'Mériel',
    'Montry',
    'Chatou',
    'Gressy',
    'Forfry',
    'Forges',
    'Poissy',
    'Bellot',
    'Brunoy',
    'Bailly',
    'Blandy',
    'Stains',
    'Gravon',
    'Antony',
    'Esmans',
    'Lisses',
    'Pamfou',
    'Andelu',
    'Sèvres',
    'Chapet',
    'Cachan',
    'Ermont',
    'Blandy',
    'Crosne',
    'Féricy',
    'Baulne',
    'Sevran',
    'Frétoy',
    'Solers',
    'Janvry',
    'Sceaux',
    'Lognes',
    'Sailly',
    'Ennery',
    'Vanves',
    'Orphin',
    'Torfou',
    'Hodent',
    'Chevru',
    'Émancé',
    'Gouaix',
    'Everly',
    'Tigery',
    'Yerres',
    'Davron',
    'Écouen',
    'Cesson',
    'Pringy',
    'Domont',
    'Drancy',
    'Rebais',
    'Saclay',
    'Saclas',
    'Chessy',
    'Dhuisy',
    'Aulnoy',
    'Meudon',
    'Quiers',
    'Thoiry',
    'Savins',
    'Thieux',
    'Le Pin',
    'Houdan',
    'Poincy',
    'Éragny',
    'Fosses',
    'Pantin',
    'Persan',
    'Bréval',
    'Moussy',
    'Rumont',
    'Poigny',
    'Torcy',
    'Flagy',
    'Nandy',
    'Melun',
    'Dugny',
    'Gagny',
    'Marcq',
    'Othis',
    'Dagny',
    'Blaru',
    'Cerny',
    'Brouy',
    'Mours',
    'Paroy',
    'Massy',
    'Barcy',
    'Orsay',
    'Paley',
    'Paris',
    'Bondy',
    'Sancy',
    'Osmoy',
    'Maule',
    'Épône',
    'Messy',
    'Nézel',
    'Issou',
    'Tilly',
    'Médan',
    'Seugy',
    'Cuisy',
    'Citry',
    'Diant',
    'Fouju',
    'Lassy',
    'Meaux',
    'Ormoy',
    'Nozay',
    'Voulx',
    'Vigny',
    'Hermé',
    'Lissy',
    'Limay',
    'Cergy',
    'Chars',
    'Bréau',
    'Linas',
    'Lardy',
    'Rosay',
    'Burcy',
    'Esbly',
    'Ablis',
    'Ichy',
    'Orly',
    'Buhy',
    'Pécy',
    'Vicq',
    'Igny',
    'Doue',
    'Cély',
    'Réau',
    'Sagy',
    'Méré',
    'Vert',
    'Osny',
    'Avon',
    'Baby',
    'Sigy',
    'Égly',
    'Ury',
    'Buc',
    'Us',
]

# Formes courtes usuelles vers le nom officiel : ce que les gens écrivent
# réellement, qui ne correspond pas toujours au libellé administratif.
ALIAS_COMMUNES = {
    "saint denis": "Saint-Denis",
    "st denis": "Saint-Denis",
    "st-denis": "Saint-Denis",
    "boulogne": "Boulogne-Billancourt",
    "levallois": "Levallois-Perret",
    "issy": "Issy-les-Moulineaux",
    "ivry": "Ivry-sur-Seine",
    "vitry": "Vitry-sur-Seine",
    "villejuif": "Villejuif",
    "asnieres": "Asnières-sur-Seine",
    "asnières": "Asnières-sur-Seine",
    "colombes": "Colombes",
    "courbevoie": "Courbevoie",
    "puteaux": "Puteaux",
    "clichy": "Clichy",
    "saint ouen": "Saint-Ouen-sur-Seine",
    "st ouen": "Saint-Ouen-sur-Seine",
    "saint-ouen": "Saint-Ouen-sur-Seine",
    "noisy": "Noisy-le-Grand",
    "champigny": "Champigny-sur-Marne",
    "maisons alfort": "Maisons-Alfort",
    "charenton": "Charenton-le-Pont",
    "nogent": "Nogent-sur-Marne",
    "fontenay": "Fontenay-sous-Bois",
    "rosny": "Rosny-sous-Bois",
    "villeneuve saint georges": "Villeneuve-Saint-Georges",
    "le kremlin bicetre": "Le Kremlin-Bicêtre",
    "kremlin bicetre": "Le Kremlin-Bicêtre",
    "cergy": "Cergy",
    "evry": "Évry-Courcouronnes",
    "évry": "Évry-Courcouronnes",
    "saint germain": "Saint-Germain-en-Laye",
    "st germain": "Saint-Germain-en-Laye",
    "neuilly": "Neuilly-sur-Seine",
    "chatenay": "Châtenay-Malabry",
    "châtenay": "Châtenay-Malabry",
}
